name: Build & Push to Docker

on: # https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions#triggering-your-deployment
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Docker meta bigbuilder
        id: meta-bigbuilder
        uses: docker/metadata-action@v5
        with:
          images: marcelosm/bigbuilder
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='US/Pacific'}}

      - name: Build and push bigbuilder
        uses: docker/build-push-action@v5
        with:
          context: .
          target: bigbuilder
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-bigbuilder.outputs.tags }}
          labels: ${{ steps.meta-bigbuilder.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker meta bigdev
        id: meta-bigdev
        uses: docker/metadata-action@v5
        with:
          images: marcelosm/bigdev
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='US/Pacific'}}

      - name: Build and push bigdev
        uses: docker/build-push-action@v5
        with:
          context: .
          target: bigdev
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-bigdev.outputs.tags }}
          labels: ${{ steps.meta-bigdev.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
